{
  "name": "International Organization of Hare Krishnas",
  "ticker": "IOHK",
  "description": "Jetzt, wo wir Ihre Aufmerksamkeit haben. Wann werden Benachrichtigungen zur Benachrichtigung der Benutzer über Gebührenänderungen zu den Hauptbrieftaschen hinzugefügt? Ihre Spenden werden an kleinere Gemeinschaftspools delegiert, nicht an IOG oder Emurgo, die privat sein sollten.",
  "homepage": "https://decentralization.io/"
}
